name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON" # Runs Every week in mon

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'MarwenLabidi'
          COUNT: 4
        env:
          GITHUB_TOKEN: ${{ secrets.HASHNODE_GITHUB_TOKEN }}
